Relax xref ANNO limitation
Currently this xref interface assumes an ANNO format of a single line
number, but versions of OTP > 23 return a tuple, resulting in a an
error like:

ERROR: xref failed while processing /Users/jay/repos/couchdb/src/snappy: {'EXIT',
 {{badmatch,
   [{attribute,{1,1},file,{"src/snappy.erl",1}},

This relaxes the assumption on any particular ANNO format and accepts
them all.